version: '3'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./sqldata:/docker-entrypoint-initdb.d
    ports:
      - "3000:3306"
    environment:
       MYSQL_DATABASE: 'booktrade'
       MYSQL_ROOT_PASSWORD: 'Rothyu980908'
  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"
  web:
    build: .
    command: ./scripts/start_server.sh
    entrypoint: ./scripts/docker_entry.sh db 3306
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis