# Generated by Django 2.2.1 on 2019-05-27 01:29

import BookTradeWeb.storage
import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('origin_price', models.IntegerField(default=1)),
                ('sell_price', models.IntegerField(default=1)),
                ('category', models.CharField(max_length=100)),
                ('book_introduction', models.TextField(blank=True, default='')),
                ('book_image', models.ImageField(default='/headers/default.jpg', storage=BookTradeWeb.storage.OverWriteStorage, upload_to=books.models.RenameBookImagePath)),
                ('ISBN', models.CharField(max_length=100)),
                ('book_url', models.URLField(blank=True, max_length=100)),
                ('publisher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
