# Generated by Django 2.2.1 on 2019-06-11 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_shoppingcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
