# Generated by Django 2.2.1 on 2019-06-13 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_book_publish_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_option', models.TextField(default='', max_length=100)),
                ('post_address', models.TextField(blank=True)),
                ('post_code', models.TextField(blank=True, default='')),
                ('status', models.TextField(blank=True)),
                ('complete_time', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('buy_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_book_side', to=settings.AUTH_USER_MODEL)),
                ('sell_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_book_side', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
