# Generated by Django 2.2.1 on 2019-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookoffer',
            name='complete_book_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookoffer',
            name='complete_price',
            field=models.IntegerField(default=0),
        ),
    ]
