# Generated by Django 2.2.1 on 2019-06-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190613_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookoffer',
            name='contact_phone',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shoppingcar',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shoppingcar',
            name='contact_phone',
            field=models.TextField(default=''),
        ),
    ]
