# Generated by Django 2.2.1 on 2019-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_creditaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_status',
            field=models.IntegerField(default=0),
        ),
    ]
