# Generated by Django 2.2.1 on 2019-06-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20190617_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_need', to='books.Book')),
            ],
        ),
    ]
