# Generated by Django 2.2.2 on 2019-06-18 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChattingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('recv_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recv_message_side', to=settings.AUTH_USER_MODEL)),
                ('send_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_message_side', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
