# Generated by Django 2.2.1 on 2019-05-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='headers', verbose_name='header_image'),
        ),
    ]
