# Generated by Django 2.2.2 on 2019-06-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0003_auto_20190527_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
